/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddHandleDate: typeof import('./src/components/AddHandleDate.vue')['default']
    AiSummaryModal: typeof import('./src/components/AiSummaryModal.vue')['default']
    ContentCard: typeof import('./src/components/aiComp/ContentCard.vue')['default']
    ContentCardGroup: typeof import('./src/components/aiComp/ContentCardGroup.vue')['default']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    HistoryContentCard: typeof import('./src/components/aiComp/HistoryContentCard.vue')['default']
    InfoCard: typeof import('./src/components/infoCard/index.vue')['default']
    SetTaskNodeTop: typeof import('./src/components/taskMain/SetTaskNodeTop.vue')['default']
    Setting: typeof import('./src/components/Setting.vue')['default']
    SingleTaskHidden: typeof import('./src/components/settingComp/SingleTaskHidden.vue')['default']
    TaskFilter: typeof import('./src/components/TaskFilter.vue')['default']
    TaskList: typeof import('./src/components/TaskList.vue')['default']
    Tree: typeof import('./src/components/Tree.vue')['default']
  }
}
